import { useState, useEffect } from 'react'
import { getMyLetters } from '../../services/employeeService'
import { useAuth } from '../../context/AuthContext'
import { jsPDF } from 'jspdf'

async function generateLetterPDF(letter, user) {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' })
  const pageW = 210
  const margin = 20
  const contentW = pageW - margin * 2

  let logoBase64 = null
  try {
    const resp = await fetch('/shnoor-logo.png')
    const blob = await resp.blob()
    logoBase64 = await new Promise(resolve => {
      const reader = new FileReader()
      reader.onload = () => resolve(reader.result)
      reader.readAsDataURL(blob)
    })
  } catch (e) {}

  doc.setFillColor(15, 118, 110)
  doc.rect(0, 0, pageW, 38, 'F')
  if (logoBase64) doc.addImage(logoBase64, 'PNG', margin, 8, 22, 22)
  doc.setTextColor(255, 255, 255)
  doc.setFontSize(16)
  doc.setFont('helvetica', 'bold')
  doc.text('SHNOOR INTERNATIONAL LLC', logoBase64 ? margin + 27 : margin, 18)
  doc.setFontSize(9)
  doc.setFont('helvetica', 'normal')
  doc.text('HR Management System', logoBase64 ? margin + 27 : margin, 25)
  doc.text(new Date(letter.generated_at).toLocaleDateString('en-GB', { day: '2-digit', month: 'long', year: 'numeric' }), pageW - margin, 25, { align: 'right' })

  doc.setFillColor(240, 253, 250)
  doc.rect(margin, 48, contentW, 12, 'F')
  doc.setTextColor(15, 118, 110)
  doc.setFontSize(12)
  doc.setFont('helvetica', 'bold')
  doc.text(letter.title || letter.letter_type, margin + 5, 57)

  doc.setTextColor(51, 65, 85)
  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')
  const lines = doc.splitTextToSize(letter.content, contentW)
  let y = 72
  for (const line of lines) {
    if (y > 270) { doc.addPage(); y = 20 }
    doc.text(line, margin, y)
    y += 6
  }

  doc.setDrawColor(15, 118, 110)
  doc.line(margin, 282, pageW - margin, 282)
  doc.setTextColor(148, 163, 184)
  doc.setFontSize(8)
  doc.text('This is an official document generated by SHNOOR HRMS.', pageW / 2, 287, { align: 'center' })

  doc.save(`${letter.letter_type}_${user.first_name}_${user.last_name}.pdf`.replace(/ /g, '_'))
}

const TYPE_COLORS = {
  'Warning Letter': 'bg-red-50 text-red-600',
  'Appreciation Letter': 'bg-green-50 text-green-600',
  'Offer Letter': 'bg-blue-50 text-blue-600',
  'Appointment Letter': 'bg-purple-50 text-purple-600',
}

function EmployeeLetters() {
  const { user } = useAuth()
  const [letters, setLetters] = useState([])
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    getMyLetters()
      .then(res => setLetters(res.data.data || []))
      .catch(console.error)
      .finally(() => setLoading(false))
  }, [])

  if (loading) return <div className="flex items-center justify-center h-64"><p className="text-gray-400">Loading...</p></div>

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-bold text-gray-800">My Letters</h1>
        <p className="text-sm text-gray-400 mt-1">Official letters issued to you by HR</p>
      </div>

      {letters.length === 0 ? (
        <div className="bg-white rounded-xl shadow-sm border border-gray-100 p-10 text-center">
          <p className="text-gray-400 text-sm">No letters have been issued to you yet.</p>
        </div>
      ) : (
        <div className="bg-white rounded-xl shadow-sm border border-gray-100">
          <div className="overflow-x-auto">
            <table className="w-full">
              <thead>
                <tr className="text-xs text-gray-400 border-b border-gray-100 bg-gray-50">
                  <th className="text-left px-6 py-3 font-medium">Letter Type</th>
                  <th className="text-left px-6 py-3 font-medium">Title</th>
                  <th className="text-left px-6 py-3 font-medium">Issued On</th>
                  <th className="text-left px-6 py-3 font-medium">Action</th>
                </tr>
              </thead>
              <tbody>
                {letters.map(l => (
                  <tr key={l.id} className="border-b border-gray-50 hover:bg-gray-50 transition">
                    <td className="px-6 py-4">
                      <span className={`text-xs font-medium px-2.5 py-1 rounded-full ${TYPE_COLORS[l.letter_type] || 'bg-teal-50 text-teal-700'}`}>
                        {l.letter_type}
                      </span>
                    </td>
                    <td className="px-6 py-4 text-sm text-gray-700">{l.title}</td>
                    <td className="px-6 py-4 text-sm text-gray-500">
                      {new Date(l.generated_at).toLocaleDateString('en-GB')}
                    </td>
                    <td className="px-6 py-4">
                      <button onClick={() => generateLetterPDF(l, user)}
                        className="text-xs bg-teal-600 hover:bg-teal-700 text-white font-semibold px-3 py-1.5 rounded-lg transition">
                        Download PDF
                      </button>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      )}
    </div>
  )
}

export default EmployeeLetters